;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; 
;;; PP1 -- 11_excercises.lisp -- řešení úloh k cvičení 11
;;;

#|
Do tohoto souboru pište řešení úloh z cvičení. Soubor se bude při každém 
spuštění aplikace načítat, takže všechny definice budou k dispozici.

Pokud je v některé definici chyba, soubor se nenačte a aplikace chybu
oznámí. Pak je možné ji opravit a soubor načíst ručně z menu (Evaluate
All Expressions) nebo klávesovou zkratkou.

Nově vytvořené definice vždy hned vyhodnoťte (menu Evaluate Expression
nebo Evaluate All Expressions) a otestujte v Listeneru.

Chybné a rozpracované definice můžete uzavírat do komentářů tak, jak to
je uděláno s tímto textem (víceřádkový komentář) nebo s nadpisem souboru
nahoře (jednořádkový komentář).
|#

;; Testy funkcionální grafiky
;; Testy jsou v komentářích, vyhodnocujte je jeden po druhém.

#|

(im-segment)
(im-gap)

(im-rotated (im-segment) (/ pi 4))
(im-scaled (im-segment) 1/2)
(im-normalized (im-rotated (im-segment) (/ pi -6)))

(im-hflipped (im-normalized (im-rotated (im-segment) (/ pi -6))))

(im-chain (im-segment)
          (im-rotated (im-segment) (/ pi 4))
          (im-rotated (im-segment) (* pi 3/4))
          (im-rotated (im-segment) pi))

(im-split (im-segment)
          (im-scaled (im-rotated (im-segment) (/ pi 5)) 2/3)
          (im-scaled (im-rotated (im-segment) (/ pi -5)) 2/3))

(im-vflipped
 (im-split (im-segment)
           (im-scaled (im-rotated (im-segment) (/ pi 5)) 2/3)
           (im-scaled (im-rotated (im-segment) (/ pi -5)) 2/3)))

|#

(defun tree-1 (n)
  (if (= n 0)
      nil
    (im-split (im-segment) 
              (im-scaled (im-rotated (tree-1 (1- n)) (/ pi 5)) 2/3)
              (im-scaled (im-rotated (tree-1 (1- n)) (/ pi -5)) 2/3))))

;; šetrnější k paměti:
(defun tree (n)
  (if (= n 0)
      nil
    (let ((gr (tree (- n 1))))
      (im-split (im-segment) 
                (im-scaled (im-rotated gr (/ pi 5)) 2/3)
                (im-scaled (im-rotated gr (/ pi -5)) 2/3)))))

#|
(tree 1)
(tree 2)
(tree 3)
(tree 5)

(im-scaled (tree 12) 0.6)


(im-normalized (im-row (tree 2) (tree 2) (tree 2) (tree 2)))
(im-scaled (im-row (tree 12) (im-gap) (tree 12)) 1/3)
(im-scaled  (im-row (tree 12) (im-scaled (im-gap) 1/2) (tree 12)) 1/3)

(im-column (tree 2) (im-vflipped (tree 2)))

|#


#|


(im-closed (im-chain (im-segment)
                     (im-rotated (im-segment) (/ pi 4))
                     (im-rotated (im-segment) (* pi 3/4))
                     (im-rotated (im-segment) pi)))

;; pozor:
(im-filled (im-segment))

(im-filled (im-chain (im-segment)
                     (im-rotated (im-segment) (/ pi 4))
                     (im-rotated (im-segment) (* pi 3/4))
                     (im-rotated (im-segment) pi)))

|#


;; pravidelný mnohoúhelník, m je počet vrcholů
(defun reg-polygon (m)
  (labels ((rp (n)
             (if (= n 0)
                 nil
               (im-chain (im-segment) 
                         (im-rotated (rp (1- n))
                                     (/ (* 2 pi) m))))))
    (im-closed (im-rotated (rp (1- m)) (/ pi -2)))))

#|

(reg-polygon 3)
(reg-polygon 5)

|#

(defun polygonal-spiral (m n)
  (if (= n 0)
      nil
    (im-chain (im-segment) 
              (im-rotated (im-scaled (polygonal-spiral m (- n 1))
                                     9/10)
                          (/ (* 2 pi) m)))))

#|
(polygonal-spiral 3 1)
(polygonal-spiral 3 2)
(polygonal-spiral 3 3)
(polygonal-spiral 3 8)
(im-normalized (polygonal-spiral 3 30))
(polygonal-spiral 5 30)
|#

(defun square ()
  (reg-polygon 4))

#|
(square)

(im-split (square) (im-rotated (square) (/ pi 2)))

(im-split (im-split (square) (im-rotated (square) (/ pi 2)))
          (square))

(im-normalized
 (im-split (im-split (im-split (im-split (square) (im-rotated (square) (/ pi 2)))
                               (square))
                     (im-rotated (square) (/ pi -2)))
           (im-rotated (square) pi)))

(im-deck (square) (im-normalized (im-rotated (square) (/ pi 4))))

|#


(defun squares (n)
  (if (= n 0)
      nil
    (im-deck (square)
             (im-normalized (im-rotated (squares (1- n)) (/ pi 30))))))

#|    
(im-scaled (squares 50) 2)
|#


;; Pythagorův strom
(defun pythagoras (n)
  (if (= n 0)
      nil
    (let ((tree2 (im-scaled (pythagoras (1- n)) (sqrt 1/2))))
      (im-split (im-split (im-filled (square))
                          (im-rotated tree2 (/ pi 4)))
                (im-rotated (im-hflipped tree2) (/ pi -4))))))

#|
(pythagoras 1)
(pythagoras 2)
(im-scaled (pythagoras 5) 1/3)
(im-scaled (pythagoras 6) 1/3)
(im-scaled (pythagoras 7) 1/3)
(im-scaled (pythagoras 10) 1/3)
(im-scaled (pythagoras 15) 1/3)
|#

(defun triangle ()
  (reg-polygon 3))

#|
(triangle)
(im-filled (triangle))
|#

(defun triplicated (obj)
  (im-column (im-row obj obj) obj))

(defun sierp (n)
  (if (zerop n)
      (im-filled (triangle))
    (triplicated (im-scaled (sierp (1- n)) 1/2))))

#|
(im-scaled (sierp 4) 2)
(im-scaled (sierp 6) 2)
(im-scaled (sierp 8) 2)
|#

(defun koch-polygon (n)
  (if (zerop n)
      (im-rotated (im-segment) (/ pi -2))
    (let ((next (im-scaled (koch-polygon (1- n)) 1/3)))
      (im-chain next
                (im-rotated next (/ pi 3))
                (im-rotated next (/ pi -3))
                next))))

#|
(koch-polygon 2)
(koch-polygon 3)
(koch-polygon 4)

(im-scaled (koch-polygon 6) 2.5)
|#

(defun better-koch-polygon (n)
  (if (zerop n)
      (im-rotated (im-segment) (/ pi -2))
    (let ((next (im-scaled (koch-polygon (1- n)) 1/3)))
      (im-brow next
               (im-rotated next (/ pi 3))
               (im-rotated next (/ pi -3))
               next))))

;;ZK:
;;1:vyhodnotí se sám na sebe: T
;;let vs let*:
;;(let ((a 2) (b (* 2 a)))
;  (* a b))
;(let ((a 2))
 ; (let ((b (* a 2)))
 ;   (* a b)))
(let* ((a 2) (b (* 2 a)))
  (* a b))
;;
(defun zk-list-tails (list)
  (if (null (cdr list)) (cdr list)
    (cons (copy-list (cdr list)) (zk-list-tails (cdr list)))))
(defun zk-new-from-two (seq)
  (lambda (n) (* (mem seq n)
                 (mem seq (+ n 1)))))
(defun zk-all-intervals (lower upper)
  (if (> lower upper) '()
    (append (zk-all-intervals-help lower lower upper) (zk-all-intervals (+ 1 lower) upper))))
(defun zk-all-intervals-help (start curr end)
  (if (> curr end) '()
    (cons (cons start curr) (zk-all-intervals-help start (+ 1 curr) end))))
(defun all-intervals (a b)
  (if (> a b)
      '()
    (append (all-intervals-h a a b)(all-intervals (+ a 1) b))))

(defun all-intervals-h (start current end)
  (if (> current end)
      '()
    (cons (cons start current) (all-intervals-h start (+ current 1) end))))
(defun square-spiral (n)
  (if (= n 0) nil
    (im-chain (im-segment)
              (im-rotated 
               (im-scaled 
(square-spiral (- n 1)) 3/4) (/ pi 2)))))
(defun my-if (a b c)
  (if a b c))
(defun zk-interval (left right)
  (if (> (max (lower-bound left) (lower-bound right))
         (min (upper-bound left) (upper-bound right)))
      (list nil)
    (interval (max (lower-bound left) (lower-bound right))
              (min (upper-bound left) (upper-bound right)))))
(defun random-numb-p (pred)
  (let ((n (random 100)))
    (if (funcall pred n) n
      (random-numb-p pred))))
(defun zk-zero-row-p (tbl row)
  (labels ((iter (col)
             (cond ((> col 9) t)
                   ((= 0 (funcall tbl row col)) (iter (+ 1 col)))
                   (t nil))))
    (iter 0)))
(let ((p (cons 3 4)))
  (cons (cons 1 p) (cons p 2)))
(defun interleave (l1 l2)
  (If (or (null l2) (null l1)) nil 
    (cons (car l1)
          (cons (car l2)(interleave (cdr l1) (cdr l2))))))
(defun pascal-row (row)
  (if (= row 0) (list 1)
    (pascal-row-help row 0)))
(defun pascal-row-help (row col)
  (if (> col row) nil
    (cons (pascal row col) (pascal-row-help row (+ 1 col)))))
(defun first-less (seq1 seq2)
  (labels ((iter (index)
             (if (< (mem seq1 index) (mem seq2 index)) index
               (iter (+ 1 index)))))
    (iter 0)))
(defun list-to-num (list)
  (labels ((iter (list acc)
             (if (null list) acc
               (iter (cdr list) (+ (car list) (* 10 acc))))))
    (iter list 0)))
(defun count-zk (list)
  (cond ((consp list) (+ (count-zk (car list)) (count-zk (cdr list))))
        ((null list) 1)
        (t 0)))
(defun every (list pred)
  (or (null list)
      (and (funcall pred list)
           (every (cdr list) pred))))
(defun seq-count-if-zk (seq n pred)
  (labels ((iter (i)
             (cond ((= i n) 0)
                   ((funcall pred (mem seq i)) (1+ (iter (+ 1 i))))
                   (t (iter (+ i 1))))))
    (iter 0)))
(defun each-2nd (list)
  (if (null list) nil
    (cons (car list)
          (odd-conses (cdr list)))))
(defun trianglp (a b c)
  (labels ((compare (x y)
             (> x y)))
    (and (compare (+ a b) c)
         (compare (+ b c) a)
         (compare (+ a c) b))))
(defun some (pred list)
  (and (not (null list))
       (or (funcall pred (car list))
           (some pred (cdr list)))))
(defun my-list-tails (list)
  (if (null (cdr list)) (cdr list)
    (cons (copy-list (cdr list))
          (my-list-tails (cdr list)))))
(defun transpose-pair (x)
  (cond ((consp x) (cons (transpose-pair (cdr x)) (car x)))
        (t x)))
(defun zk-digit-sum (n)
  (zk-digit-sum-help n (- (digit-count n) 1)))
(defun zk-digit-sum-help (n i)
  (if (< i 0) 0
    (+ (digit n i) 
       (zk-digit-sum-help n (- i 1)))))
(defun zk-div-9 (n)
  (or (= n 9) (= n 0)
      (and (< 9 n) (zk-div-9 (zk-digit-sum n)))))
(defun zk-div-3 (n)
  (or (= n 0) (= n 3) (= n 9) (= n 6)
      (and (< 9 n) (zk-div-3 (zk-digit-sum n)))))
                    
  

(defun last-n (list n)
  (last-n-k list list n)) 

(defun last-n-k (fast slow counter)
  (cond ((null fast)
         (if (= counter 0) slow counter))
        ((> counter 0) (last-n-k (cdr fast) slow (- counter 1)))
        (t (last-n-k (cdr fast) (cdr slow) counter))))
(defun triangle (v1 v2 v3)
  (list v1 v2 v3))
(defun v1 (triangle)
  (car triangle))
(defun v2 (triangle)
  (car (cdr triangle)))
(defun v3 (triangle)
  (car (cdr (cdr triangle)))) 

(defun triangle-center (triangle)
  (point (/ (+ (point-x (v1 triangle))
               (point-x (v2 triangle))
               (point-x (v3 triangle)))
            3)
         (/ (+ (point-y (v1 triangle ))
               (point-y (v2 triangle))
               (point-y (v3 triangle)))
            3)))
(defun my-sum-zk-digit (n)
  (labels ((iter (i)
             (if (< i 0) 0
               (+ (digit n i) (iter (- i 1))))))
    (iter (- (digit-count n) 1))))
(defun diff-sum-digit (n)
  (if (< n 10) n
    (+ (rem n 10)
       (diff-sum-digit (div n 10)))))
(defun even-elements (list)
  (cond ((null list) '())
        ((funcall #'evenp (car list)) (cons (car list)
                                            (even-elements (cdr list))))
        (t (even-elements (cdr list)))))

(defun my-set-inter-2 (set1 set2)
  (cond ((or (null set1) (null set2)) nil)
        ((elementp (car set1) set2) (cons (car set1) (my-set-inter-2 (cdr set1) set2)))
        (t (my-set-inter-2 (cdr set1) set2))))
(defun my-set-inter (set1 &rest sets)
  (foldr #'my-set-inter-2 sets set1))
(defun my-seq-interleave (seq1 seq2)
  (lambda (n) (if (evenp n) (mem seq1 (/ n 2))
                                 (mem seq2 (div n 2)))))
(defun self () (function self))
(defun sum-of-sq-tree(n)
  (labels ((iter (i acc)
             (cond ((= n 0) t)
                   ((= acc n) t)
                   ((> acc n) nil)
                   ((> i (sqrt n)) nil)
                   (t (or (iter (+ 1 i) acc)
                          (iter (+ 1 i) (+ (power2 i) acc)))))))
    (iter 0 0)))
(defun column (n tbl)
  (apply #'mapcar #'nth n tbl)) 
(defun list-to-numb-3 (list)
  (labels ((iter (list acc)
           (if (null list) acc
             (iter (cdr list) (+ (car list) (* 10 acc))))))
    (iter list 0)))
(defun list-to-num-4 (list)
  (labels ((iter (list acc)
             (if (null list) acc
               (iter (cdr list) (+ (car list) (* 10 acc))))))
    (iter list 0)))
(defun every2 (pred list)
  (or (null list)
      (and (funcall pred (car list))
           (every2 pred (cdr list)))))
(defun seq-find-zk (seq pred)
  (labels ((iter (index)
             (if (funcall pred (mem seq index)) index
               (iter (+ 1 index)))))
    (iter 0)))
(defun make-counter (n)
  (labels ((count (list)
             (cond ((null list) 0)
                   ((= n (car list)) (1+ (count (cdr list))))
                   (t (count (cdr list))))))
    (lambda (list) (count list))))
                      
(defun my-reverse (list)
  (my-revappend-2 list nil))
(defun my-revappend-2 (l1 l2)
  (if (null l1) l2
    (cons (my-revappend-2 (cdr l1) l2)
          (car l1))))
(defun my-reverse-4 (list)
  (foldr (lambda (element acc) (append acc (list element)))
         list nil))
                   
(defun m-list (list)
  (if (null list) nil
    (cons (foldr #'* list 1)
          (m-list (cdr list)))))

(defun trianglpp (a b c)
(labels ((compare (x y)
           (< x y)))
 (and (compare a (+ b c))
      (compare b (+ c a))
      (compare c (+ a b)))))
(defun euler (n)
  (euler-help n 1 1 0))

(defun euler-help (n i curr acc)
  (if (> i n) acc
    (euler-help n (+ i 1) (/ curr (+ i 1)) (+ curr acc))))
(defun sums-zk (list n)
  (cond ((= n 0) 1)
        ((null list) 0)
        ((< n 0) 0)
        (t (+ (sums-zk (cdr list) n)
              (sums-zk (cdr list) (- n (car list)))))))
(defun each2nd (list)
  (if (null list) nil
    (cons (car list) (odd-conses (cdr list)))))
(defun my-odd-conses (list)
  (if (null list) nil
    (each2nd (cdr list))))
(defun mein-seq-count (seq n pred)
  (labels ((iter (i)
             (cond ((= i n) 0)
                   ((funcall pred (mem seq i)) (+ 1 (iter (+ i 1))))
             (t (iter (+ i 1))))))
    (iter 0)))
               
(defun seq-shift (seq shift)
  (lambda (n) (let ((move (- n shift)))
                (if (< move 0) 0 (mem seq move)))))
(defun seq-shift-next (seq shift)
  (lambda (n) (if (< (- n shift) 0) 0 (mem seq (- n shift)))))


(defun tails(list)
  (if (null list) '()
    (cons (copy-list list)
          (tails (cdr list)))))
(defun mein-reverse (list)
  (foldr (lambda (el acc) (if (null list) nil (append acc (list el)))) list nil))
(defun same-sum-p (lists)
  (or (null lists)
      (null (cdr lists))
      (apply #'=
             (mapcar (lambda (sub) (apply #'+ sub))
                     lists))))
(defun seq-pred-10 (pred n seq)
  (labels ((iter (i)
             (cond ((= i n) nil)
                   ((funcall pred (mem seq i)) i)
                   (t (iter (+ i 1))))))
    (iter 0)))
(defun m-list-8 (list)
  (if (null list) '()
    (cons (foldr #'* list 1)
          (m-list-8 (cdr list)))))
(defun listo-numero (list)
  (labels ((iter (list acc)
             (if (null list) acc
               (iter (cdr list) (+ (car list) (* 10 acc))))))
    (iter list 0)))
(defun star (n)
  (star-help (/ pi n) n))
(defun star-help (deg n)
  (if (= n 0) nil
    (im-deck (im-rotated (im-segment) (* deg n))
             (star-help deg (- n 1)))))
(defun my-square-spiral (n)
  (if (= n 0) nil
    (im-chain (im-segment)
               (im-rotated (im-scaled (my-square-spiral (- n 1)) 3/4) (/ pi 2)))))
(defun mein-square (n)
  (if (= n 0) nil
    (im-chain (im-segment)
              (im-rotated (im-scaled (mein-square (- n 1)) 3/4) (/ pi 2)))))
(defun mein-star (n)
(mein-star-help n (/ pi n)))
(defun mein-star-help (n deg)
  (if (= n 0) nil
    (im-deck (im-rotated (im-segment ) (* n deg))
             (mein-star-help (- n 1) deg))))
(defun tree-height (tree)
  (if (null (node-children tree)) 0
    (+ 1 (tree-list-max (node-children tree)))))
(defun digitssum (n)
  (if (< n 10) n
    (+ (rem n 10)
       (digitssum (div n 10)))))
(defun intervalinter (i1 i2)
  (let ((l (max (lower-bound i1) (lower-bound i2)))
        (u (min (upper-bound i1) (upper-bound i2))))
    (if (> l u) nil
      (interval l u))))
(defun compress (list)
  (cond ((null list) nil)
        ((null (cdr list)) (list (cons (car list) 1)))
        ((eql (car list)
              (car (cdr list)))
         (let ((res (compress (cdr list))))
           (cons (cons (car list)
                       (1+ (cdr (car res))))
                 (cdr res))))
        (t (cons (cons (car list)
                       1)
                 (compress (cdr list))))))
(defun compress2 (list)
  (cond ((null list) nil)
        ((null (cdr list)) (list (cons (car list) 1)))
        ((eql (car list) (car (cdr list)))
         (let ((res (compress2 (cdr list))))
           (cons (cons (car list) (1+ (cdr (car res))))
                 (cdr res))))
        (t (cons (cons (car list) 1)
                 (compress (cdr list))))))
(defun mistrospirale (n)
  (if (= n 0) nil
     (im-chain (im-segment)
              (im-rotated (im-scaled (mistrospirale (- n 1)) 3/4) (/ pi 2))) ))
(defun sumero-digits (n)
  (labels ((iter (i)
             (if (< i 0) 0
               (+ (digit n i)
                  (iter (- i 1))))))
    (iter (- (digit-count n) 1))))
(defun sumero-digitale (n)
  (if (< n 10) n
    (+ (rem n 10)
       (sumero-digitale (div n 10)))))
(defun my-seq-interleave (seq1 seq2)
  (lambda  (n) (if (evenp n) (mem seq1 (div n 2)
                               )
                 (mem seq2 (div n 2)))))
(defun self-return ()
  (function self-return))
(defun listtails1 (list)
  (if (null list) nil
    (cons (copy-list list)
          (listtails1 (cdr list)))))
(defun listtails2 (list)
  (if (null (cdr list)) (cdr list)
            (cons (copy-list (cdr list))
                  (listtails2 (cdr list)))))
(defun list-numero (list)
  (labels ((iter (list acc)
             (if (null list) acc
               (iter (cdr list) (+ (car list) (* 10 acc))))))
    (iter list 0)))
(defun mein-revappend (l1 l2)
  (if (null l1) l2
    (mein-revappend (cdr l1) 
          (cons (car l1) l2))))
(defun mein-rev (l)
  (mein-revappend l nil))
(defun mein-reverse3 (l)
  (foldr (lambda (el acc) (append acc (list el))) list nil))
(defun sum-of-squares-wo (&rest numbs)
  (foldr #'+ (mapcar #'power2 numbs) 0))
(defun mein-rem (a b)
  (- a (* (floor (/ a b)) b)))
(defun seq-to-shifted (seq shift)
  (lambda (n) (if (< (- n shift) 0) 0
                (mem seq (- n shift)))))
(defun sums (list n)
  (cond ((= n 0) 1)
        ((null list) 0)
        (t (+ (sums (cdr list) n)
              (sums (cdr list) (- n (car list)))))))
(defun sums2 (list n)
  (cond ((zerop n) 1)
        ((or (null list) (< n 0)) 0)
        (t (+ (sums2 (cdr list) n)
              (sums2 (cdr list) (- n (car list)))))))
(defun same-sumsss-p (lists)
  (or (null lists) 
      (null (cdr lists))
      (apply #'= (lambda (sup) (mapcar (apply#'+ sub))) lists)))
(defun star3 (n)
  (labels ((star-help (deg n)
             (if (= n 0) nil
               (im-deck (im-rotated (im-segment) (* n deg))
                        (star-help deg (- n 1))))))
    (star-help (/ pi n) n)))
  

(defun sum-sq-p (n)
(labels ((iter (i acc)
           (cond ((= n 0) t)
                 ((= acc n) t)
                 ((> acc n) nil)
                 ((> i (sqrt n)) nil)
                 (t (or (iter (+ 1 i) acc)
                        (iter (+ 1 i) (+ (power2 i) acc)))))))
  (iter 0 0)))
(defun sum-sq-9 (&rest numbs)
  (foldr #'+ (mapcar #'power2 numbs) 0))
(defun my-comp (list)
  (cond ((null list) nil)
        ((null (cdr list)) (list (cons (car list) 1)))
        ((eql (car list) (car (cdr list)))
         (let ((res (my-comp (cdr list))))
           (cons (cons (car list) (1+ (cdr (car res))))
                 (cdr res))))
         (t (cons (cons (car list) 1)
                  (my-comp (cdr list))))))
(defun div-by-3 (n)
  (or (= n 3) (= n 6) (= n 9) (= n 0)
      (and (> n 9) (div-by-3 (3digit-sum n)))))
(defun 3digit-sum (n)
  (labels ((iter (i)
             (if (< i 0) 0
               (+ (digit n i) (iter (- i 1))))))
    (iter (- (digit-count n) 1))))
(defun szn (list k n)
  (cond ((null list) nil)
        ((> k 0) (szn (cdr list) (- k 1) n))
        ((> n 0) (cons (car list) (szn (cdr list) 0 (- n 1))))
        (t nil)))
(defun star-n (n)
(star-n-helper (/ pi n) n))
(defun star-n-helper (deg n)
  (if (= n 0) nil
    (im-deck (im-rotated (im-segment ) (* deg n))
             (star-n-helper deg (- n 1)))))
(defun div3 (n)
  (labels ((digit-sum (i) 
             (if (< i 0) 0
               (+ (digit n i) (digit-sum (- i 1))))))
    (or (= n 0) (= n 3) (= n 6) (= n 9)
        (and (> n 9) (div3 (digit-sum (- (digit-count n) 1)))))))
(defun trianglp2 (a b c)
  (labels ((bigger (x y)
             (> x y)))
    (and (bigger (+ a b) c)
         (bigger (+ b c) a)
         (bigger (+ c a) b))))
(defun list-tail2 (list)
  (if (null list) nil
    (cons (copy-list list)
          (list-tail2 (cdr list)))))
(defun subintervals2 (left right)
  (if  (> left right) nil
    (append (subintervals2-helper left left right)
            (subintervals2 (+ 1 left) right))))
(defun subintervals2-helper (start current end)
  (if (> current end) nil
    (cons (cons start current)
          (subintervals2-helper start (+ 1 current) end))))
(defun some (list pred)
  (cond ((null list) nil)
        ((funcall pred (car list)) t)
        (t (some (cdr list) pred))))
(defun some2 (list pred)
  (and (not (null list))
       (or (funcall pred (car list))
            (some2 (cdr list) pred))))
(defun seq-pred-2 (seq)
  (lambda (n) (* (mem seq n)
                 (mem seq (+ 1 n)))))
(defun sq-spiral (n)
  (if (= n 0) nil
    (im-chain (im-segment)
              (im-rotated (im-scaled (sq-spiral (- n 1)) 3/4) (/ pi 2)))))
(defun list-to-numero22 (list)
  (labels ((iter (list acc)
             (if (null list) acc
               (iter (cdr list) (+ (car list) (* acc 10))))))
    (iter list 0)))
(defun sumslist22 (n list)
  (cond ((= n 0) 1)
        ((null list) 0)
        (t (+ (sumslist22 n (cdr list))
           (sumslist22 (- n (car list)) (cdr list))))))
(defun every22 (list pred)
  (or (null list)
        (and (funcall pred (car list))
             (every22 (cdr list) pred))))
(defun each2nd (list)
  (if (null list) nil
    (cons (car list) (oddconses (cdr list)))))
(defun oddconses (list)
  (if (null list) nil
    (each2nd (cdr list))))
(defun seq-count-if-22 (seq pred n )
  (labels ((iter (i)
             (cond ((= i n) 0)
                   ((funcall pred (mem seq n)) (+ 1 (iter (+ 1 i))))
                   (t (iter (1+ i))))))
    (iter 0)))
  

;;final repe
(defun last-n (list n)
(last-n-helper list list n))
(defun last-n-helper (fast slow count)
  (cond ((null fast) (if (= count 0) slow count))
        ((> count 0) (last-n-helper (cdr fast) slow (- count 1)))
        (t (last-n-helper (cdr fast) (cdr slow) count))))
(defun tree-hei (node)
  (1+ (tree-hei-help (cdr node))))
(defun tree-hei-help (nodes)
  (if (null nodes) 0
    (+ (tree-hei (car nodes))
       (tree-hei-help (crd nodes)))))
(defun my-tree-hei (tree)
  (if (null (node-children tree)) 0
    (+ 1 (max-tree-list (node-children tree)))))
(defun max-tree-list (roots)
  (if (null roots) 0
    (max (my-tree-hei (car roots))
         (max-tree-list (cdr roots)))))

                      
(defun my-count-if (seq p n)
  (labels ((iter (i)
             (cond ((= i n) 0)
                   ((funcall p (mem seq i)) (+ 1 (iter (+ 1 i))))
                   (t (iter (+ i 1))))))
    (iter 0)))
(defun seq-count-if3 (seq n test)
  (labels ((counter (c)
             (cond ((> c n) 0)
                   ((funcall test (mem seq c)) (1+ (counter (1+ c))))
                   (t (counter (1+ c))))))
    (counter 0)))
(defun my-primep (n)
  (labels ((iter (n i)
             (cond ((= n 2) t)
                   ((= i n) t)
                   ((= 0 (rem n i)) nil)
                   (t (iter n (+ 1 i))))))
    (iter n 2)))
(defun summ3 (list)
  (if (null (cdr list)) (cons 0 nil)
    (cons (foldr #'+ (cdr list) 0)
          (summ3 (cdr list)))))
(defun deph (struc)
  (if (atom struc) 0
    (1+ (max (deph (car struc))
            (deph (cdr struc))))))
                  
(defun depth (struct)
 (if (atom struct)
	      0
	    (1+ (max (depth (car struct)) (depth (cdr struct))))))
(lambda (n) (funcall (lambda (self n) (if (= n 0) 1 
                                        (* n (funcall self self (- n 1)))))
                       (lambda (self n) (if (= n 0) 1 
                                          (* n (funcall self self (- n 1))))) 
    n))

(let ((f (lambda (fun n) (if (= n 0) 1
                           (* n (funcall fun fun (- n 1)))))))
         
  (funcall f f 3))

           
(defun column (n lists)
  (if (null lists) nil
    (mapcar (lambda (list) (funcall #'nth n list)) lists)))
(defun column2 (n lists)
  (if (null lists) nil
    (mapcar (lambda (list) (funcall #'nth n list)) lists)))
(defun my-make-counter (n)
  (labels ((iter (list)
             (cond ((null list) 0)
                   ((= (car list) n) (+ 1 (iter (cdr list))))
                   (t (iter (cdr list))))))
    (lambda (list) (iter list))))
(defun my-reverso (list)
  (labels ((my-rev (l1 l2)
             (if (null l1) l2
               (my-rev (cdr l1) (cons (car l1) l2)))))
    (my-rev list nil)))
(defun my-m-list (list)
  (if (null list) nil
    (cons (foldr '* list 1)
          (my-m-list (cdr list)))))
(defun same-sums22 (lists)
  (cond ((null lists) t)
        ((null (cdr lists)) t)
        (t (apply #'= 
                  (mapcar (lambda (sub) (foldr #'+ sub 0)) lists)))))
(defun same-sum-p (lists)
  (or (null lists)
      (null (cdr lists))
      (apply #'=
             (mapcar (lambda (sub) (apply #'+ sub))
                     lists))))
(defun lasttt(list n)
  (cond ((null list) n)
        ((= n 0) nil)
        ((= n 1) list)
        (t (lasttt (cdr list) (- n 1)))))
(defun lastest (list n)
  (cond ((null list) n)
        ((= n 0) nil)
        ((= n 1) list)
        (t (lastest (cdr list) (- n 1)))))
(defun make-arit (a1 n d acc)
  (if (= n 0) (reverse acc)
    (make-arit (+ a1 d) (- n 1) d (cons a1 acc))))
(defun makearit2 (a1 n d)
  (make-arit a1 n d nil))
(defun counter (n)
  (labels ((count (list)
             (cond ((null list) 0)
                   ((= n (car list)) (1+ (count (cdr list))))
                   (t (count (cdr list))))))
    (lambda (list) (count list))))
(defun m-listo (list)
  (if (null list) nil
    (cons (apply #'* list)
          (m-listo (cdr list))))) 
(defun last (n list)
  (cond ((null list) n)
        ((= n 0) nil)
        ((= n 1) list)
        (t (last (- n 1) (cdr list)))))
(defun coltbl (lists n)
  (if (null lists) nil
    (mapcar (lambda (list) (funcall #'nth n list)) lists)))
(defun tailen (list)
  (if (null (cdr list)) nil
    (cons (cdr list)
          (tailen (cdr list)))))
(defun tailen2 (list)
  (if (null  list) nil
    (cons  list
          (tailen2 (cdr list)))))
(defun summero (list)
  (if (null list) nil
    (cons (apply #'+ list)
          (summero (cdr list)))))
(defun compress3 (list)
  (cond ((null list) nil)
        ((null (cdr list)) (list (cons (car list) 1)))
        ((eql (car list) (car (cdr list))) 
         (let ((rest (compress3 (cdr list))))
           (cons (cons (car list) (+ 1 (cdr (car rest))))
                 (cdr rest))))
        (t (cons (cons (car list) 1)
                 (compress3 (cdr list))))))
(defun counter (n)
  (labels ((count (list)
             (cond ((null list) 0)
                   ((= n (car list)) (1+ (count (cdr list))))
                   (t (count (cdr list))))))
    (lambda (list) (count list))))
(defun depth3 (struct)
  (if (atom struct) 0
    (1+ (max (depth (car struct))
             (depth (cdr struct))))))
(defun sublists5 (left ri)
  (if (> left ri) nil
    (append (sub-help left left ri)
            (sublists5 (+ 1 left) ri))))
(defun sub-help (start curr end)
 (if (> curr end) nil
  (cons (cons start curr) (sub-help start (+ 1 curr) end))))
(defun interleavelist (l1 l2)
  (if (or (null l1) (null l2))
      nil
    (cons (car l1) (cons (car l2) (interleavelist (cdr l1) (cdr l2))))))
(defun interleavel (l1 l2)
  (if (or (null l1) (null l2)) nil
      (cons (car l1) (cons (car l2) (interleavel (cdr l1) (cdr l2))))))
(defun facttolist (n)
  (labels ((iter (i acc)
             (cond ((= i n) nil)
                   ((= i 0) (cons 1 (iter (+ i 1) acc)))
                   (t (cons (* i acc) (iter (+ i 1) (* i acc)))))))
    (iter 0 1)))
(defun fiblist (n)
  (labels ((iter (i curr prev)
             (cond ((= i n) nil)
                   ((= i 0) (cons 0 (iter (+ 1 i) curr prev)))
                   ((= i 1) (cons 1 (iter (+ 1 i) curr prev)))
                   (t (cons (+ curr prev) (iter (+ i 1) (+ prev curr) curr))))))
    (iter 0 1 1)))
(defun samesublists (lists)
  (cond ((null lists) t)
        ((null (cdr lists)) t)
        (t (apply #'= (mapcar (lambda (sublist) (apply #'+ sublist)) lists)))))
(defun factorials10 (n)
  (labels ((iter (i acc)
             (cond ((= i n) nil)
                   ((= i 0) (cons 1 (iter (+ 1 i) acc)))
                   (t (cons (* i acc) (iter (+ i 1) (* acc i)))))))
    (iter 0 1)))
(defun fibtolist10 (n)
  (labels ((iter (i curr prev)
             (cond ((= i n) nil)
                   ((= i 0) (cons 0 (iter (+ 1 i) curr prev)))
                   ((= i 1) (cons 1 (iter (+ 1 i) curr prev)))
                   (t (cons (+ curr  prev) (iter (+ i 1) (+ curr prev) curr))))))
    (iter 0 1 0)))
(lambda (n)
  (funcall
   (lambda (self n)
     (if (= n 0)
         1 
       (* n (funcall self self (- n 1)))))
   (lambda (self n)
     (if (= n 0)
         1 
       (* n (funcall self self (- n 1)))))
  n))
         
(defun y (x)
  (if (consp x)
      (cons (y (cdr x))
            (y (car x)))
x))
(defun list-tails (list)
  (if (null (cdr list)) nil
    (cons (cdr list) (list-tails (cdr list)))))
(defun new-from-two (seq)
  (lambda (n) (* (mem seq n) (mem seq (+ n 1)))))
(defun intervaly (left right)
  (if (> left right) '()
      (append (intervaly-help left left right)
              (intervaly (+ left 1) right))))
(defun intervaly-help (start curr end)
  (if (> curr end) nil
      (cons (cons start curr) (intervaly-help start (+ 1 curr) end))))

(defun tree-height3 (tree)
  (if (null (node-children tree))
      0
    (+ 1 (tree-list-max (node-children tree)))))

(defun tree-list-max (roots)
  (if (null roots)
      0
    (max (tree-height3 (car roots))(tree-list-max (cdr roots)))))

(defun square-sp (n)
  (if (= n 0) nil
    (im-chain (im-segment)
              (im-rotated (im-scaled (square-sp (- n 1)) 3/4) (/ pi 2)))))
(defun my-if (a b c)
  (if a b c))
(defun interval (left right)
  (cons left right))
(defun left (interval)
  (car interval))
(defun right (interval)
  (cdr interval))
(defun interval-intersection (int1 int2)
  (let ((x (max (left int1) (left int2)))
        (y (min (right int1) (right int2))))
    (if (> x y) nil
      (interval x y))))
(defun random-number-p (pred)
  (let ((n (random 100)))
    (if (funcall pred n) n
      (random-number-p pred))))
(defun zero-row-pp (tbl row)
  (labels ((iter (column)
             (cond ((> column 9) t)
                   ((= 0 (funcall tbl row column)) (iter (+ 1 column)))
                   (t nil))))
    (iter 0)))
(defun interleave (list1 list2)
  (cond ((null list1) list2)
        ((null list2) list1)
        (t (cons (car list1)
                 (cons (car list2) (interleave (cdr list1) (cdr list2)))))))
(defun my-pascal (row column)
  (if (or (= 0 row) (= 0 column) (= row column)) 1
    (+ (my-pascal (- row 1) column)
       (my-pascal (- row 1) (- column 1)))))
(defun pascal-row (row)
  (labels ((iter (col)
             (if (> col row) nil
               (cons (my-pascal row col) (iter (+ 1 col))))))
    (iter 0)))
(defun pasc-row (row)
  (if (= row 0) '(1)
    (let ((prev (pascal-row (- row 1))))
      (cons 1 (mapcar '+ prev 
                      (append (cdr prev) '(0)))))))
(defun first-less (seq1 seq2)
  (labels ((iter (index)
             (if (< (mem seq1 index) (mem seq2 index)) index
               (iter (+ 1 index)))))
    (iter 0)))
(defun max-path (node)
  (if (null (node-children node))
      (list (node-value node))
    (cons (node-value node)(find-longest (mapcar #'max-path (node-children node))))))

(defun find-longest (paths)
  (if (null paths)
      nil
    (let ((path1 (node-value paths))
          (path2 (find-longest (node-children paths))))
      (if (< (length path1) (length path2))
          path2
        path1))))
(defun divibleby3 (n)
  (or (= n 0) (= n 3) (= n 6) (= n 9)
      (and (> n 9) (divibleby3 (digit-sum n)))))
(defun digit-sum (n)
  (labels ((iter (i)
             (if (< i 0) 0
    (+ (digit n i) (iter (- i 1))))))
  (iter (- (digit-count n) 1))))
(defun divby3 (n)
  (labels ((iter (i)
             (if (< i 0) 0
               (+ (digit n i) (iter (- i 1))))))
    (or (= n 0) (= n 3) (= n 6) (= n 9)
        (and (< 9 n) (divby3 (iter (- (digit-count n) 1)))))))
   
(defun trianglppp (a b c)
  (labels ((compare (x y)
             (> x y)))
    (and (compare (+ a b) c)
         (compare (+ a c) b)
         (compare (+ b c) a))))
(defun tails (list)
  (if (null list) nil
    (cons list
          (tails (cdr list)))))

(defun transpose-pair (x)
  (if (consp x)
	(cons (transpose-pair (cdr x))
		(transpose-pair (car x)))
    x))
(defun sub-intervals (left ri)
 (if (> left ri) nil
   (append (sub-int-help left left ri) (sub-intervals (+ 1 left) ri))))
(defun sub-int-help (start curr end)
  (if (> curr end) nil
    (cons (cons start curr) (sub-int-help start (+ 1 curr) end))))
(defun last-n (list n)
(last-n-helper list list n))
  
(defun last-n-helper (slow fast count)
  (cond ((null fast) (if (= count 0) slow count))
        ((> count 0) (last-n-helper slow (cdr fast) (- count 1)))
        (t (last-n-helper (cdr slow) (cdr fast) count))))
(defun some (list pred)
  (and (not (null list))
       (or (funcall pred (car list))
           (some (cdr list) pred))))
(defun seq-pred-2 (seq)
  (lambda (n) ( * 
                (mem seq n) 
                (mem seq (+ 1 n)))))
(defun list-to-number (list)
  (labels ((iter (list acc)
             (if (null list) acc
               (iter (cdr list) (+ (car list) (* 10 acc))))))
    (iter list 0)))
(defun sums (n list)
  (cond ((= n 0) 1)
        ((null list) 0)
       (t  (+ (sums n (cdr list))
           (sums (- n (car list)) (cdr list))))))
(defun count (list)
  (cond ((consp list) (+ (count (car list)) (count (cdr list))))
        ((null list) 1)
        (t 0)))
(defun every (list pred)
  (or (null list)
      (and (funcall pred (car list))
           (every (cdr list) pred))))
                         
(defun each-2nd (list)
  (cond ((null list)
         '())
        ((null (cdr list)) (cons (car list) '()))
        (t (cons (car list)
          (each-2nd (cddr list))))))
(defun each2nd (list)
  (cond ((null list) nil)
        ((null (cdr list)) (cons (car list) nil))
        (t (cons (car list)
                 (each2nd (cddr list))))))
(defun seq-count-if-3 (pred seq n)
  (labels ((iter (i)
             (cond ((= i n) 0)
                   ((funcall pred (mem seq i)) (1+ (iter (1+ i))))
                   (t (iter (1+ i))))))
    (iter 0)))
(defun tree-level (tree n)
  (if (= n 0) (list (node-value tree))
    (tree-list-level (node-children tree) (- n 1))))
(defun tree-list-level (trees n)
  (if (null trees) nil
    (append (tree-level (car trees) n)
            (tree-list-level (node-children trees) n))))
(defun triangllp (a b c)
  (labels ((bigger (x y)
             (> x y)))
    (and (bigger (+ a b) c)
         (bigger (+ a c) b)
         (bigger (+ b c) a))))
  
(defun my-signum (n)
  (if (or (> n 0) (< n 0)) 1
        (t 0)))

(defun euler (n)
  (euler-help n 0 1 0))
(defun euler-help (n i curr acc)
  (if (> i n) acc
    (euler-help n (+ i 1) (/ curr (+ i 1)) (+ acc curr))))

(defun same-sums-pp (lists)
  (apply #'= (mapcar (lambda (n) (apply #'+ n)) lists)))

(defun my-sum (list)
  (labels ((s (n len)
             (if (> n len) 0
    (+ (nth n list) (s (+ n 1) len)))))
    (s 0 (length list))))
(defun my-reverse (list)
  (labels ((revappend (l1 l2)
             (if (null l1) l2
               (revappend (cdr l1) (cons (car l1) l2)))))
    (revappend list nil)))
(defun seq-shift (seq shift)
  (lambda (n) (if (< (- n shift) 0) 0 (mem seq (- n shift)))))





(defun prefix-to-infix (list)
  (cond ((atom list) list) ;;není to seznam jen číslo nebo symbol 5 nebo x treba tak ten list vratim
        ((or (null (cdr list))(null (cdr (cdr list))))(mapcar #'prefix-to-infix list));;kdyz ma seznam jen 1 prvek nebo ma jen 2 prvky operator a arg treba (+ 1)...unární operátor, nema klasicky tvar (op ar1 ar2)...NEDĚLÁM infix protože nemám 2 argumenty->aplikuje funkci na kazdy prvek seznamu
        (t (let ((op (car list))
                 (args (mapcar #'prefix-to-infix (cdr list))))

             (foldl (lambda (a b) 
                      (list a op b))
                    (cdr args) (car args)))))) ;;treti vetev je normalni prefixovy vyraz-list neni atom a ma aspon 3 prvky, car=operator, cdr=argumenty kromě operátoru, mapcar je rekurzivně převede na infix-kdyby byly vnořené výrazy, lambda vytvori infix, 
;;musi tam byt foldl aby se to skladalo zleva ...u + a * by nevadil foldr ale u deleni atd by to vadilo


(defun my-tree-height (node)
  (if (null (node-children node)) 0
    (1+ (apply #'max (mapcar #'my-tree-height (node-children node))))))




;;maximalni delka cesty ve stromě:
;;max-path
(defun longer (a b)
  (if (> (length a) (length b)) a b))
(defun my-max-path-list (nodes)
  (if (null (cdr nodes)) (max-path (car nodes))
    (longer (max-path (car nodes))
            (my-max-path-list (cdr nodes)))))
(defun max-path (node)
  (if (null (node-children node)) (list (node-value node))
      (cons (node-value node)
            (my-max-path-list (node-children node))))))

;;trojuhelnik konstruktor+selektory a funkce triangl center:
(defun point (a b)
  (cons a b))
(defun point-x (point)
  (car point))
(defun point-y (point)
  (cdr point))
(defun triangle (v1 v2 v3)
  (list v1 v2 v3))
(defun v1 (triangle)
  (car triangle))
(defun v2 (triangle)
  (car (cdr triangle)))
(defun v3 (triangle)
  (car (cdr (cdr triangle))))
(defun triangle-centre (triangle)
  (point (/ (+ (point-x (v1 triangle))
               (point-x (v2 triangle))
               (point-x (v3 triangle)))
            3)
         (/ (+ (point-y (v1 triangle))
               (point-y (v2 triangle))
               (point-y (v3 triangle)))
            3)))


;;sum-digits
;;s floor a rem:
(defun sum-digits (number)
  (if (< number 10) number
    (+ (rem number 10)
       (sum-digits (div number 10)))))
;;rem 10 vrati posledni cifru, div 10 odsekne posledni cifru
;bez divu s floorem:
(defun sum-digits1 (number)
  (if (< number 10) number
    (+ (rem number 10)
       (sum-digits1 (floor (/ number 10))))))
;;bez remu, flooru a divu:
(defun sum-digits2 (number)
  (labels ((iter (i)
             (if (< i 0) 0
                   (+ (digit number i) (iter (- i 1))))))
    (iter (- (digit-count number) 1))))
;;even-elements
(defun even-elements (list)
  (cond ((null list) nil)
        ((funcall #'evenp (car list)) (cons (car list) (even-elements (cdr list))))
        (t (even-elements (cdr list)))))

;;mnozina=list...usporadane vzestupne
;;my-set-intersection2 vrati prunik
(defun my-intersection2 (set1 set2)
  (cond ((or (null set1) (null set2)) nil)
        ((elementp (car set1) set2) (cons (car set1) (my-intersection (cdr set1) set2)))
        (t (my-intersection2 (cdr set1) set2))))
;;bez elememtu:
(defun my-int2 (set1 set2)
  (cond ((or (null set1) (null set2)) '())
        ((< (car set1) (car set2)) (my-int2 (cdr set1) set2))
        ((> (car set1) (car set2)) (my-int2 set1 (cdr set2)))
        (t (cons (car set1)
                 (my-int2 (cdr set1) (cdr set2))))))
;seq-interleave vrací pslp ve ktere se stridaji cleny 1 a 2 pslp:
(defun seq-interleave (seq1 seq2)
  (lambda (n) (if (evenp n) (mem seq1 (div n 2))
                (mem seq2 (div n 2)))))
(defun intersections (set1 &rest sets)
  (foldr #'my-intersection2 sets set1))
;;find-path hledani cesty ve stromu 
(defun find-path (node el)
  (if (eql el (node-value node)) (list (node-value node))
         (let((subpath (find-path-in-children (node-children node) el)))
             (if (null subpath) nil
               (cons (node-value node) subpath)))))
(defun find-path-in-children (nodes el)
  (if (null nodes) nil
    (or (find-path (car nodes) el)
        (find-path-in-children (cdr nodes) el))))

;;node=tree


;;self funkce bez parametrů
(defun selfreturn ()
  (function selfreturn))
(defun square-spiral (n)
  (if (= n 0) nil
    (im-chain (im-segment)
              (im-rotated (im-scaled (square-spiral (- n 1)) 3/4) (/ pi 2)))))
(defun list-tails (list)
(if (null list) nil
  (cons list
        (list-tails (cdr list)))))
(defun vec-+ (vec &rest vecs)
  (foldr #'vec-+-2 vecs vec))
 
(defun antilistp (antilist)
  (or (eql antilist nil)
      (and (consp antilist)
           (antilistp (car antilist)))))
(defun last-n (list n)
(last-help list list n))
(defun last-help (fast slow count)
  (cond ((null fast)
         (if (= count 0) slow count))
        ((> count 0) (last-help (cdr fast) slow (- count 1)))
        (t (last-help (cdr fast) (cdr slow) count))))
(defun compress (list)
  (cond ((null list) nil)
        ((null (cdr list)) (cons (car list) 1))
        ((eql (car list) (car (cdr list)))
         (let ((rest (compress (cdr list))))
             (cons (cons (car list) (1+ (cdr (car rest))))
                   (cdr rest))))
        (t (cons (cons (car list) 1)
                 (compress (cdr list))))))
                   
                       
  
(defun sum-squares (&rest args)
  (foldr #'addsq args 0))
(defun addsq (x acc)
  (+ (power2 x) acc))

(defun sublist (list k n)
  (cond ((or (= 0 n)(null list)) nil)
        ((> k 0) (sublist (cdr list) (- k 1) n))
        (t (cons (car list)
                 (sublist (cdr list) 0 (- n 1))))))

(defun my-gcd (a b)
  (if (= b 0) a
    (my-gcd b (rem a b))))
(defun my-reverse (list)
  (labels ((my-revappend (l1 l2)
             (if (null l1) l2
              (my-revappend (cdr l1) (cons (car l1) l2)))))
    (my-revappend list nil)))
           
    
(defun my-set-intersection (set1 set2)
  (cond ((or (null set1) (null set2)) nil)
        ((> (car set1) (car set2)) (my-set-intersection set1 (cdr set2)))
        ((< (car set1) (car set2)) (my-set-intersection (cdr set1) set2))
        (t (cons (car set1) (my-set-intersection (cdr set1) (cdr set2))))))
(defun my-set-intersection-el (set1 set2)
  (cond ((or (null set1) (null set2)) nil)
        ((elementp (car set1) set2) (cons (car set1) (my-set-intersection-el (cdr set1) set2)))
        (t (my-set-intersection-el (cdr set1) set2))))

(defun my-rev (list)
  (labels ((my-rev (l1 l2)
             (if (null l1) l2
               (my-rev (cdr l1) (cons (car l1) l2)))))
    (my-rev list nil)))
(defun my-reverse-2 (list)
  (foldr (lambda (x acc) (append acc (list x))) list nil))
(defun my-rev2 (list)
  (foldr (lambda (x acc) (append acc (list x))) list nil)
;;append spojuje seznamy
;;foldr: (f a (f b (f c acc)))
;foldr jde z prava
(defun zero-col-p (fun col)
  (labels ((iter (row)
             (cond ((> row 9) t)
                   ((= 0 (funcall fun row col)) (iter (+ 1 row)))
                   (t nil))))
    (iter 0)))
(defun column (lists index)
    (mapcar (lambda (list) (funcall #'nth index list)) lists))
(defun str (n)
  (str-hlp n (/ pi n)))
(defun str-hlp (n deg)
  (if (= n 0) nil
    (im-deck (im-rotated (im-segment) (* n deg))
             (str-hlp (1- n) deg))))
                         
(defun sq-sp (n)
  (if (= n 0) nil
   (im-chain (im-segment) (im-rotated (im-scaled (sq-sp (1- n)) 3/4) (/ pi 2)))))
;_______________________________-
(defun digit (num dig)
  (rem (div num (expt 10 dig)) 10))
(defun hypotenuse (a b)
  (sqrt (+ (power2 a) (power2 b))))
(defun minusp(n)
  (> 0 n))
(defun abs (n)
  (if (> n 0) n (- n)))
(defun point-dist (a-x a-y b-x b-y)
  (let ((x-leg (- a-x b-x))
        (y-leg (- a-y b-y)))
    (hypotenuse x-leg y-leg)))
(defun compare-bigger (a b)
  (> a b))
(defun trianglep (a b c)
  (let ((ab (+ a b))
        (bc (+ b c))
        (ca (+ c a)))
    (and (compare-bigger ab c)
         (compare-bigger ca b)
         (compare-bigger bc a))))
(defun heron (a b c)
  (let ((s (/ (+ a b c) 2)))
    (sqrt (* s (- s a) (- s b) (- s c)))))
(defun heron-cart (a-x a-y b-x b-y c-x c-y)
  (let ((a (point-dist b-x b-y c-x c-y))
        (b (point-dist a-x a-y c-x c-y))
        (c (point-dist a-x a-y b-x b-y)))
  (hero a b c)))
(defun ellipse-area (a b)
  (if (eql t b)
      (ellipse-area a a)
  (* pi a b)))
(defun ellipse-area2 (a b)
  (if (eql b t)
      (* pi a a)
    (* pi a b)))
(defun squarep (a)
  (labels ((iter (i a)
             (cond ((= a (power2 i )) t)
                   ((> (power2 i) a) nil)
                   (t (iter (1+ i) a)))))
    (iter 0 a)))
(defun squarep2 (a)
  (eql a (power2 (round (sqrt a)))))
(defun my-gcd (a b)
  (if (zerop b)
      a
    (my-gcd b (rem a b))))
(defun heron-sqrt-iter (a x epsilon)
  (let ((y (/ (+ (/ a x) x) 2)))
    (if (approx-=  a (power2 y) epsilon)
        y
      (heron-sqrt-iter a y epsilon))))
(defun heron-sq-2 (a eps)
  (heron-sqrt-iter a 1 eps))
(defun int-sum (lower upper)
  (if (> lower upper) 0
    (+ lower (int-sum (1+ lower) upper))))
(defun int-sum-tail (low upp)
  (labels ((iter (low upp ir)
             (if (> low upp) ir
               (iter (1+ low) upp (+ ir low)))))
    (iter low upp 0)))
(defun my-pow (a x)
  (labels ((iter (a x ir)
             (if (zerop x) ir
               (iter a (1- x) (* x ir)))))
    (iter a x 1)))
(defun divible9 (n)
(or (= n 9)
    (and (> n 9)
         (divible9 (digitsum n)))))
(defun digitsum (n)
  (labels ((iter (i)
                   (if (minusp i) 0
                     (+ (digit n i) (iter  (1- i))))))
         (iter (1- (digit-count n)))))
(defun lieb (epsilon)
  (labels ((iter (div eps ir sign)
             (if (< (/ 1 div) eps)
                 (* 4 ir)
               (iter (+ 2 div) eps (+ ir (* sign (/ 1 div))) (- sign)))))
    (iter 3 eps 1 -1)))
(defun star-4 (n)
  (star-4-hlp n (/  pi n)))
(defun star-4-hlp (n deg)
  (if (= 0 n) nil
  (im-deck (im-rotated (im-segment) (* deg n))
           (star-4-hlp (1- n) deg))))
(defun sq-sp (n)
  (if (zerop n) nil
  (im-chain (im-segment)
           (im-scaled (im-rotated (sq-sp (1- n)) (/ pi 2)) 3/4))))
(defun min-house()
  (im-chain (im-segment) 
            (im-scaled (im-rotated (im-segment) (/ pi 4)) (/ 1 (sqrt 2)))
            (im-scaled (im-rotated (im-segment) (* pi 3/4)) (/ 1 (sqrt 2))) 
             (im-rotated (im-segment) pi) (im-rotated (im-segment) (- (/ pi 2)))))

(defun houses (n)
  (if (zerop n) nil
    (im-row (min-house) 
            (im-gap)
            (im-scaled (houses (1- n)) 3/4))))
(defun square ()
  (labels ((iter (n)
             (if (zerop n) nil
               (im-chain (im-segment)
                         (im-rotated (iter (1- n)) (/ pi 2))))))
    (iter 4)))
(defun ctvercevsobe (n)
  (if (zerop n) nil
    (im-deck (square)
          (im-scaled (im-rotated  (ctvercevsobe (1- n)) (/ pi 4)) 2/3))))
(defun str (n)
  (labels ((iter (deg n)
             (if (zerop n) nil
               (im-deck (im-rotated (im-segment) (* deg n))
                        (iter deg (1- n))))))
    (iter (/ pi n) n)))
(defun mif (a b c)
  (if a b c))
(defun db3 (n)
  (or (or (= n 3)
               (= n 6)
               (= n 9))
      (and (> n 10)
           (db3 (dsum n)))))
(defun dsum (n)
  (labels ((iter (i)
             (if (< i 0) 0
               (+ (digit n i)
                  (iter (1- i))))))
    (iter (1- (digit-count n)))))
(defun tp (a b c)
  (labels ((comp (x y)
             (> x y)))
    (and (comp (+ a b) c)
         (comp (+ b c) a)
         (comp (+ a c) b))))
(defun lt (list)
  (if (null list) nil
    (cons list
          (lt (cdr list)))))
(defun trp (list)
  (if (consp list)
      (cons (trp (cdr list))
            (trp (car list)))
    list))
(defun subi (low upp)
  (if (> low upp) nil
    (append (subih low low upp)
          (subi (1+ low) upp))))
(defun subih (start curr end)
  (if (> curr end) nil
    (cons (cons start curr)
          (subih start (1+ curr) end))))
(defun lastn (list k)
(lastnh list list k))

      
(defun lastnh (slow fast k)
  (cond ((and (null fast) (> k 0)) k)
        ((zerop k)
         (if (null fast) slow
           (lastnh (cdr slow) (cdr fast) 0 )))
        (t (lastnh slow (cdr fast) (1- k) ))))
(defun some (pred list)
  (and (not (null list))
       (or (funcall pred (car list))
           (some pred (cdr list)))))

(defun sqp2 (seq)
  (lambda (n) (* (mem seq n) (mem seq (1+ n)))))
(defun treeh (node)
  (if (null (node-children node)) 0
    (let* ((res (mapcar #'treeh (node-children node)))
           (res2 (foldr #'max res 0)))
      (1+ res2))))
      
(defun treeh2 (node)
  (if (null (node-children node))
      0
    (1+ (treeh2h (node-children node)))))
(defun treeh2h (subtrees)
  (if (null subtrees) 0
    (max (treeh2 (car subtrees))
         (treeh2h (cdr subtrees)))))
(defun self ()
  #'self)
(defun self2 ()
  (function self2))
(defun seqintr (s1 s2)
  (lambda (n)
    (if (evenp n)
        (mem s1 (div n 2))
      (mem s2 (div n 2)))))
(defun zero (n)
  0)
(defun compres (list)
  (cond ((null list) nil)
        ((null (cdr list)) (list (cons (car list) 1)))
        ((eql (car list) (cadr list))
         (let ((res (compres (cdr list))))
          (cons (cons (car list)(1+ (cdr (car res))))
                (cdr res))))
        (t (cons (cons (car list) 1)
                 (compres (cdr list))))))
(defun ltn (lst)
  (labels ((iter (list acc)
             (if (null list) acc
               (iter (cdr list) (+ (car list) (* 10 acc))))))
    (iter lst 0)))
(defun lastnk (list pos nums)
  (labels ((iter (i list nums)
             (cond ((null list) nil)
                   ((and (> nums 0)(>= i pos)) (cons (car list) (iter (1+ i) (cdr list) (1- nums))))
                   ((> nums 0) (iter (1+ i) (cdr list) nums))
                   (t nil))))
    (iter 0 list nums)))
(defun sum-sq (n)
  (labels ((iter (i n acc)
             (cond ((zerop n) t)
                   ((= acc n) t)
                   ((> acc n) nil)
                   ((> (power2 i) n) nil)
                   (t (or (iter (1+ i) n acc)
                       (iter (1+ i) n (+ (power2 i) acc)))))))
    (iter 0 n 0)))
                   
(defun sumofsquares (&rest nums)
  (foldr #'+ (mapcar #'power2 nums) 0))
          
(defun c (list)
  (cond ((consp list) (+ (c (car list)) (c (cdr list))))
        ((null list) 1)
        (t 0)))
(defun fibbb (n)
  (labels ((iter (n i prev prev2)
             (cond ((= n 0) 0)
                   ((= n 1) 1)
                   ((= n i) (+ prev prev2))
                   (t (iter n (1+ i) (+ prev prev2) prev)))))
    (iter n 2 1 0)))
(defun column (tbl n)
  (mapcar (lambda (sublist) (nth n sublist)) tbl))
(defun intersection (s1 s2)
  (cond ((or (null s2)(null s1)) nil)
        ((> (car s1) (car s2)) (intersection s1 (cdr s2)))
        ((< (car s1) (car s2)) (intersection (cdr s1) s2))
        (t (cons (car s1)(intersection (cdr s1)(cdr s2))))))
(defun deeps (node)
  (if (null (node-children node)) (node-value node)
    (+ (node-value node) (deepslist (node-children node)))))
(defun deepslist (children)
  (if (null children) 0
    (+ (deeps (car children))
       (deepslist (cdr children)))))
(defun deepsum2 (node)
  (if (null (node-children node)) (node-value node)
    (let* ((res (mapcar #'deepsum2 (node-children node)))
          (res2 (foldr #'+ res 0)))
      (+ res2 (node-value node)))))
(defun ltnx(list)
  (labels ((iter (list acc)
             (if (null list) acc
               (iter (cdr list) (+ (car list) (* acc 10))))))
    (iter list 0)))
(defun intervals (l u)
(if (> l u) nil
  ( append (insh l l u)
           (intervals (1+ l) u))))
(defun insh (start curr end)
  (if (> curr end) nil
    (cons (cons start curr)
          (insh start (1+ curr) end))))

        
(defun every (list pred)
  (or (null list)
      (and (funcall pred (car list))
           (every (cdr list) pred))))
;neexituje prvek ktery by nesplnoval predikat
(defun ln (list n)
  (labels ((iter (slow fast n)
             (cond ((and (> n 0)(null fast)) n)
                   ((zerop n)
                    (if (null fast) slow
                      (iter (cdr slow) (cdr fast) 0)))
                   (t (iter slow (cdr fast) (1- n))))))
    (iter list list n)))
(defun trlevel (level node)
  (if (zerop level) (list (node-value node))
    (let* ((res (mapcar (lambda (sub) (trlevel (1- level) sub)) (node-children node)))
          (res2 (foldr #'append res '())))
      res2)))
(defun trlevel2 (level node)
  (if (zerop level) (list (node-value node))
    (trlevel2h (1- level) (node-children node))))
(defun trlevel2h (level children)
  (if (null children) nil
      (append (trlevel2 level (car children))
              (trlevel2h level (cdr children)))))
(defun count (el list)
  (cond ((null list) 0)
        ((eql el (car list)) (1+ (count el (cdr list))))
        (t (count el (cdr list)))))
(defun mkcounter (n)
  (labels ((iter (list)
             (count n list)))
    #'iter))
(defun mlist (list)
  (if (null list) nil
    (cons (foldr #'* list 1)
          (mlist (cdr list)))))
(defun r (l1 l2)
  (if (null l1) l2
  (r (cdr l1) (cons (car l1) l2))))
(defun ttl (node)
  (if (null (node-children node))
(list (node-value node))
    (cons (node-value node)
          (helper (node-children node)))))
(defun helper (children)
  (if (null children) nil
    (append (ttl (car children))
            (helper (cdr children)))))
(defun sames (lists)
  (apply #'= (mapcar (lambda (sublist) (foldr #'+ sublist 0)) lists)))
(defun eu (div i n acc )
  (if (< n i) acc
        (eu (* div i) (1+ i) n (+ acc (/ 1 (* i div))))))
(defun eul (n)
  (eu 1 1 n 1))
(defun my-sumy (list)
    (labels ((it (n len)
               (if (>= n len) 0
                 (+ (nth n list) (it (1+ n) len)))))
      (it 0 (length list))))
(defun pr-t-i (list)
  (cond ((null list) nil)
        ((null (cdr list)) list)
        (t (let ((op (car list))
              (args (cdr list)))
          (apply #'append (cons (car args) nil) (mapcar (lambda (arg) (append  (list op)  (list arg))) (cdr args)))))))
(defun mpath (node)
  (if (null (node-children node)) (list (node-value node))
   (cons (node-value node) (mpathch (node-children node)))))
(defun mpathch (children)
  (if (null children) nil
    (longer (mpath (car children))
         (mpathch (cdr children)))))
(defun longer (l1 l2)
  (if (> (length l2) (length l1)) l2 l1))
(defun sp (n)
(if (zerop n) nil
  (im-chain (im-segment)
            (im-rotated (im-scaled (sp (1- n)) 3/4) (/ pi 2)))))
(defun lstn (list n)
  (labels ((iter (f s n)
             (cond ((and (null f)
                         (> n 0)) n)
                   ((zerop n)
                    (if (null f) s
                      (iter (cdr f) (cdr s) 0)))
                   (t (iter (cdr f) s (1- n))))))
    (iter list list n)))
(defun nulli (i)
  (if (> (lower i) (upper i)) t nil))
(defun intersection (i1 i2)
  (if (or (nulli i1)(nulli i2)) nil
        (let ((low (max (lower i1) (lower i2)))
              (upp (min (upper i1) (upper i2))))
          (if (> low upp) nil
            (interval low upp)))))
(defun sums (n list)
  (labels ((iter (acc list)
             (cond ((= acc n) 1)
                   ((null list) 0)
                   ((> acc n) 0)
                   (t (+ (iter (+ acc (car list)) (cdr list))
                         (iter acc (cdr list)))))))
    (iter 0 list)))
(defun flat (node)
  (cond ((atom node) node)
        ((null (node-children node)) (list (node-value node)))
        (t (let* ((res (mapcar #'flat (node-children node)))
                  (res2 (foldr #'append res nil)))
             (cons (node-value node) res2)))))
(defun deeprev (node)
  (cond ((or (atom node)(listp node)) node)
        ((null (node-children node)) (node-value node))
        (t (cons (deeprevh (node-children node)) (list (node-value node))))))
(defun deeprevh (children)
  (if (null children) nil
    (append (deeprevh (cdr children))
            (list (deeprev (car children))))))

(defun deeprev3 (node)
 (if (null (node-children node)) nil
   (let ((res (mapcar (lambda (sublist) (if (atom sublist) sublist (reverse sublist))) (node-children node))))
     (append res (list (node-value node))))))
(defun deepr (node)
  (cond ((atom node) node)
        ((listp node) node)
        ((consp node)  (deepr (cons(cdr node)
                                   (car node))))))
        
(defun listp (el)
  (cond ((atom el) nil)
        (t (and (atom (car el))
                 (null (cdr el))))))
        
(defun deeprev3 (node)
  (reverse (mapcar (lambda (arg) (if (or (atom arg) (listp arg)) arg (reverse arg))) node)))
(defun pw2 (seq)
  (lambda (n) (power2 n)))
(defun pw2 (n)
  (cons (power2 n) (lambda () (pw2 (1+ n)))))
(defun koch (n)
  (if (zerop n) (im-rotated (im-segment) (/ pi 2))
    (let ((cara (koch (1- n))))
      (im-chain cara
                (im-rotated cara (-(/ pi 3)))
               (im-rotated cara  (/ pi 3))
               cara))))
(defun each2nd (list)
  (labels ((iter (i list)
             (cond ((null list) nil)
                   ((= i 2) (cons (car list) (iter 1 (cdr list))))
                   (t (iter (1+ i) (cdr list))))))
    (cons (car list) (iter 0 list))))
(defun seq-count-if (pred upp seq)
  (labels ((iter (i)
             (cond ((= i upp) 0)
                   ((funcall pred (mem seq i)) (1+ (iter (1+ i))))
                   (t (iter (1+ i))))))
    (iter 0)))
(defun euler (n)
  (labels ((iter (div acc i)
             (if (> i n) acc
                   (iter (* div i) (+ acc (/ 1 (* div i))) (1+ i)))))
    (iter 1 1 1)))
(defun same-sump (list)
  (apply #'= (mapcar (lambda (sublist) (foldr #'+ sublist 0)) list)))
(defun maxpath (node)
  (if (null (node-children node)) (list (node-value node))
    (let* ((res (mapcar #'maxpath (node-children node)))
           (res2 (foldr #'longer res nil)))
      (append (list (node-value node)) res2))))
      
(defun prefixinfix(list)
  (cond ((null list) nil)
        ((or (null (cddr list))(null (cdr list))) list)
        (t (let ((op (car list))
                 (args (cdr list)))
           (apply #'append (list (car args)) (mapcar (lambda (arg) (append (list op) (list arg))) (cdr args)))))))
(defun seqshift(sq sh)
  (lambda (n) (if (< (- n sh) 0) 0 (mem sq (- n sh)))))
(defun seq-find (low upp seq pred)
  (labels ((iter (i)
             (cond ((> i upp) nil)
                   ((funcall pred (mem seq i)) i)
                   (t (iter (1+ i))))))
    (iter low)))
(defun div9 (n)
  (or (= n 9)
      (and (> n 10)
           (div9 (digit-sum n)))))
(defun digitsum (n)
  (labels ((iter (i)
             (if (< i 0) 0
                   (+ (digit n i) (iter (1- i))))))
    (iter (1- (digit-count n)))))
(defun rev(l)
  (labels ((iter (l n)
            (if  (null l) n
              (iter (cdr l) (cons (car l) n)))))
    (iter l nil)))
(defun rev2 (list)
  (foldr (lambda (x acc) (append acc (list x))) list nil))
(defun mkcounter (n)
  (labels ((iter (list)
             (cond ((null list) 0)
                   ((= n (car list)) (1+ (iter (cdr list))))
                   (t (iter (cdr list))))))
    #'iter))
(defun reverse1 (list)
  (labels ((revappend (list n)
             (if (null list) n
               (revappend (cdr list) (cons (car list) n)))))
    (revappend list nil)))
(defun my-rev (list)
  (foldr (lambda (el acc) (append acc (list el))) list nil))
(defun ml (list)
  (if (null list) nil
    (cons (foldr #'* list 1)
          (ml (cdr list)))))
(defun spir (n)
  (if (zerop n) nil
    (im-chain (im-segment)
              (im-scaled (im-rotated (spir (1- n)) (/ pi 2)) 3/4))))
(defun tree-to-list (node)
  (if (null (node-children node)) (list (node-value node))
    (let* ((res (mapcar #'tree-to-list (node-children node)))
         (res2 (foldr #'append res nil)))
      (cons (node-value node) res2))))
(defun list-to-n (list)
  (labels ((iter (acc list)
             (if (null list) acc
               (iter (+ (car list) (* 10 acc)) (cdr list)))))
    (iter 0 list)))
(defun subintervals (low upp)
  (if (> low upp) nil
    (append (subintervalsh low low upp)
            (subintervals (1+ low) upp))))
(defun subintervalsh (start curr end)
  (if (> curr end)
      nil
    (cons (cons start curr)
          (subintervalsh start (1+ curr) end))))
(defun every (pred list)
  (or (null list)
      (and (funcall pred (car list))
           (every pred (cdr list)))))
(defun last-n (list n)
  (labels ((iter (fast slow n)
             (cond ((and (null fast) (> n 0)) n)
                   ((zerop n)
                    (if (null fast) slow
                      (iter (cdr fast) (cdr slow) 0)))
                   (t (iter (cdr fast) slow (1- n))))))
    (iter list list n)))
(defun tree-levl(node level)
  (if (zerop level) (list (node-value node))
    (let* ((res (mapcar (lambda (x) (tree-levl x (1- level))) (node-children node)))
          (res2 (foldr #'append res nil)))
      res2)))
(defun sum-of-sqs (n)
  (labels ((iter (i acc)
             (cond ((= 0 n) t)
                   ((= n acc) t)
                   ((> acc n) nil)
                   ((> (power2 i) n) nil)
                   (t (or (iter (1+ i) (+ (power2 i) acc))
                          (iter (1+ i) acc))))))
    (iter 0  0)))
;listy mnoziny prunik:
(defun inters (l1 l2)
  (cond ((or (null l2) (null l1)) nil)
        ((> (car l1) (car l2)) (inters l1 (cdr l2)))
        ((< (car l1) (car l2)) (inters (cdr l1) l2))
        (t (cons (car l1) (inters (cdr l1) (cdr l2))))))
(defun next (n)
  (cons (* n (+ 1 n)) (lambda () (next (1+ n)))))
(defun deepsum (node)
  (if (null (node-children node)) (node-value node)
    (let* ((res (mapcar #'deepsum (node-children node)))
          (res2 (foldr #'+ res (node-value node))))
      res2)))
(defun star (n)
  (labels ((iter (deg n)
             (if (zerop n) nil
               (im-deck (im-rotated (im-segment) (* deg n))
                        (iter deg (1- n))))))
    (iter (/ pi n) n)))
(defun spiral8 (n)
  (if (zerop n) nil
    (im-chain (im-segment)
              (im-scaled (im-rotated (spiral8 (1- n)) (/ pi 2)) 3/4))))
(defun interleavelist (l1 l2)
  (cond ((null l1) l2)
        ((null l2) l1)
        (t (cons (car l1) (cons (car l2)
                                (interleavelist (cdr l1) (cdr l2)))))))
(defun pasrow (n)
  (if (= n 0) '(1)
        (let ((prev (pasrow (1- n))))
           (mapcar #'+ (append prev (list 0))
              (cons 0 prev)))))
(defun removesubtree (pred node)
  (if (null (node-children node)) 
         (if (funcall pred (node-value node)) nil (list (node-value node)))
        (let* ((res (mapcar (lambda (el) (removesubtree pred el)) (node-children node)))
              (res2 (remove-if #'null  res)))
          (res2)))
(defun rempredtree (pred node)
  (cond ((null (node-children node))
         (if (funcall pred (node-value node))
             nil
           (list (node-value node))))
        (t (if (funcall pred (node-value node)) (append (list  (node-value node)) (rempredtreel pred (node-children node))) (append (list (node-value node)) (rempredtreel pred (node-children node)))))))
(defun rempredtreel (pred children)
  (if (null children) nil
    (append (list (rempredtree pred (car children)))
          (rempredtreel pred (cdr children)))))
(defun remstree (pred node)
  (cons (node-value node)
        (remstree2 pred (node-children node))))
(defun remstree2 (pred children)
  (cond ((null children) nil)
        ((funcall pred (node-value (car children)))
             (remstree2 pred (cdr children)))
        (t (cons (remstree pred (car children))
                 (remstree2 pred (cdr children))))))
(defun compress(list)
  (cond ((null list) nil)
        ((null (cdr list)) (list (cons (car list) 1)))
        ((eql (car list) (car (cdr list)))
         (let ((res (compress (cdr list))))
           (cons (cons (car list) (+ 1 (cdr (car res))))
                 (cdr res))))
        (t (cons (cons (car list) 1)
                 (compress (cdr list))))))
(defun union (s1 s2)
  (cond ((null s1) s2)
        ((null s2) s1)
        ((elementp (car s1) s2)(union (cdr s1) s2))
        (t (cons (car s1)
                 (union (cdr s1) s2)))))

(defun treelevel(level node)
  (if (zerop level) (list (node-value node))
        (let* ((res (mapcar (lambda (x) (treelevel (1- level) x)) (node-children node)))
              (res2 (foldr #'append res nil)))
          res2)))
(defun rev (list)
  (foldr (lambda (x acc) (append acc (list x))) list nil))
(defun interleave (seq1 seq2)
  (lambda (n) (if (evenp n)
                  (mem seq1 (div n 2))
                (mem seq2 (div n 2)))))
(defun intrleave (l1 l2)
  (cond ((null l1) l2)
        ((null l2) l1)
        (t (cons (car l1) (cons (car l2) (intrleave (cdr l1) (cdr l2)))))))
(defun intersection (l1 l2)
  (cond ((or (null l1) (null l2)) nil)
        ((elementp (car l1) l2) (cons (car l1) (intersection (cdr l1) l2)))
        (t (intersection (cdr l1) l2))))
(defun intersection3 (l1 l2)
  (cond ((or (null l1) (null l2)) nil)
        ((> (car l1) (car l2)) (intersection3 l1 (cdr l2)))
        ((< (car l1) (car l2)) (intersection3 (cdr l1) l2))
        (t (cons (car l1) (intersection3 (cdr l1) (cdr l2))))))
(defun sublistp (sublist list)
  (cond ((null sublist) t)
        ((null list) nil)
        ((eql (car sublist) (car list)) (sublistp (cdr sublist) (cdr list)))
        (t (sublistp sublist (cdr list)))))
(defun findp (node val)
  (cond ((null node) nil)
        ((eql (node-value node) val)
         (list (node-value node)))
        (t (let ((res (findph (node-children node) val)))
             (if (null res) nil
               (cons (node-value node)
                     res))))))
(defun findph (children val)
  (cond ((null children) nil)
        (t (let ((res (findp (car children) val)))
           (if (null res)
               (findph (cdr children) val)
             res)))))
(defun nthlist (list n)
  (labels ((iter (i list )
             (cond ((null list) nil)
                   ((= i n) (cons (car list)
                                  (iter 0 (cdr list))))
                   (t (iter (1+ i) (cdr list))))))
    (cons (car list)
          (iter 0 list))))
(defun some (pred list)
  (and (not (null list))
      (or (funcall pred (car list))
          (some pred (cdr list)))))
(defun euler (n)
  (labels ((iter (div n i acc)
             (if (> i n) acc
                   (iter (* i div) n (1+ i) (+ acc (/ 1 (*  i div)))))))
    (iter 1 n 1 1)))
               
(defun foldl (fun list init)
  (if (null list) init
  (foldl fun (cdr list) (funcall fun (car list) init))))

(defun prtinf (list)
  (cond ((null list) nil)
        ((null (cdr list)) list)
        ((and (symbolp (car list))
             (null (cddr list))
             (atom(cadr list))) list)
        (t (let ((op (car list))
              (args (cdr list)))
          (apply #'append (list (car args)) (mapcar (lambda (x) (append (list op) (list x))) (cdr args)))))))
(defun reverseee (l1)
  (foldl #'cons l1 nil))
(defun foldr (fun list init)
  (if (null list) init
    (funcall fun (car list) (foldr fun (cdr list) init))))
(defun app (&rest lists)
  (foldr (lambda (x acc) (foldr #'cons x acc)) lists nil))
(defun count-if-tree (pred node)
  (cond ((and (not (funcall pred (node-value node)))(null (node-children node))) 0)
        ((funcall pred (node-value node)) (1+ (helper pred (node-children node))))
        (t (helper pred (node-children node)))))
(defun helper (pred children)
  (if (null children) 0
    (+ (count-if-tree pred (car children))
       (helper pred (cdr children)))))
(defun findpath (val node)
  (cond ;((null node) nil)
        ((eql val (node-value node)) (list (node-value node)))
        (t (let ((res (findpathch val (node-children node))))
             (if (null res)
                 nil
               (cons (node-value node)
                     res))))))
(defun finpath (val node)
  (if (eql (node-value node) val) (list (node-value node))
    (let ((res (findpathch val (node-children node))))
      (if (null res) nil
        (cons (node-value node) res)))))
(defun findpathch (val ch)
  (if (null ch) nil
    ;(let ((res (findpath val (car ch))))
     ; (if (null res)
          (or (findpath val (car ch))
              (findpathch val (cdr ch)))))
        ;res))))
(defun floorsqrt (n)
  (labels ((iter (i)
             (if (> (power2 i) n) (1- i)
               (iter (1+ i)))))
    (iter 0)))
;(fact by lambda
(funcall 
  (lambda (fun n)
    (if (zerop n) 1
      (* n (funcall fun fun (1- n)))))
  (lambda (fun n)
    (if (zerop n) 1
    (* n (funcall fun fun (1- n))))) 3)
(defun digit  (n d)
(labels ((iter (i n d)
           (if (= d i) (rem n 10)
                 (iter (1+ i) (div n 10) d))))
  (iter 0 n d)))
(defun digitcount(n)
  (if (> 10 n) 1
    (+ 1 (digitcount (div n 10)))))
(defun listcdrs (list)
  (if (null (cdr list)) nil
    (cons (cdr list)
          (listcdrs (cdr list)))))
(defun eachnnnd (list)
  (if (null list) nil
    (cons (car list)
          (eachnnnd (cddr list)))))
(defun depth (struct)
  (if (atom struct) 0
    (1+ (max (depth (car struct))
             (depth (cdr struct))))))
(defun treeh (node)
  (if (null (node-children node)) 0
    (let* ((res (mapcar #'treeh (node-children node)))
          (res2 (foldr #'max res 0)))
  (1+ res2))))
(defun sums (list)
  (if (null list) (list 0)
    (cons (apply #'+ list)
          (sums (cdr list)))))
(defun usm2 (list)
  (if (null list) (list 0)
    (let ((res (usm2 (cdr list))))
      (cons (+ (car list) (car res)) res))))
(defun depth (struct)
  (if (atom struct) 0
        (+ 1 (max (depth (car struct)) (cdr struct)))))

(defun seq (seq1 seq2)
  (lambda (n) (if (evenp n) (mem seq1 (n div 2)) (mem seq2 (n div 2)))))
(defun  self ()
  #'self)
